name: Check external links
on:
  workflow_dispatch:
  schedule:
    - cron: "20 4 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        base-branch: 'main'
        config-file: '.github/markdown-external-links.config.json'
  open-issue:
    runs-on: ubuntu-latest
    needs: [markdown-link-check]
    if: always()
    steps:
      - name: Open Github Issue for broken links
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const actionUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/attempts/${context.runAttempt || 1}`;
            await github.rest.issues.create({
              owner,
              repo,
              title: 'Links are broken in the documentation',
              body: `Some links are broken in the Markdown documentation. Check the [action result](${actionUrl}).`
            });
